name: vinylgarage
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.4
  path_provider: ^2.0.11
  sqflite: ^2.2.0+3
  animated_splash_screen: ^1.3.0
  image_picker: ^0.8.6
  intl: 0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true


  fonts:
    - family: Rozha One
      fonts:
        - asset: fonts/RozhaOne-Regular.ttf
    - family: Sanchez
      fonts:
        - asset: fonts/Sanchez-Regular.ttf